### ISSUE TITLE
EXCEPTION: Error in :0:0 caused by: pdfMake is not defined

### ISSUE THREAD

**Issue by sterben13** [BennyFranco/ng-pdf-make#1] opened 2017-05-15 01:19 UTC

**Comment by BennyFranco** [comment] 2017-05-15 01:41
Can you send me more details or the stack trace to reproduce the exception please? @sterben13

**Comment by tonychangcheng** [comment] 2017-05-17 05:55
I got the same issue. I fixed it by adding the pdfmake.min.js (node_modules/pdfmake/build/pdfmake.min.js)

**Comment by tonychangcheng** [comment] 2017-05-17 06:08
And the vfs_fonts.js

**Comment by boom235** [comment] 2017-05-23 13:44
hm, I have the same problem. But this does not look like a good solution for a productive environment...

**Comment by BennyFranco** [comment] 2017-05-23 14:01
@boom235 npm must install PDFmake as a dependency automatically, for some reason this isn't happening, i'm checking that, for now adding that manually like @tonychangcheng is a solucion.

**Comment by boom235** [comment] 2017-05-24 07:52
Well before I use that module and import the pdfmake-data manually, I will just use pdfmake and write my own service.

**Comment by KertOjasaar** [comment] 2017-10-10 18:04
I'm trying to use ng-pdf-make and since there's no 'build' folder, I manually added the 2 aforementioned .js files to ng-pdf-make/pdfmake, but I'm still getting an error saying 'pdfMake is not defined (pdfmake.service.js)'. I also tried adding 'declare var pdfMake: any;' u=to typings.d.ts (somebody recommended that), but still getting the same error.
How could I fix this? I followed [this tutorial](https://www.npmjs.com/package/ng-pdf-make) to install and set up everything.
The error occurs when trying to use open, print or download.

**Comment by JPedroMG** [comment] 2017-11-28 19:44
where i have to add it @tonychangcheng, @BennyFranco ?

**Comment by alivalinasab** [comment] 2018-01-05 00:41
This solution fixed my issue.

https://stackoverflow.com/questions/28584455/including-pdfmake-in-client-side-of-mean-stack-project

**Comment by AmineBena17** [comment] 2018-06-20 14:58
@alivalinasab 

I've already tried your solution but it still not working, i have the same problem.


`MyAppraisalsComponent.html:1 ERROR ReferenceError: pdfMake is not defined
    at PdfmakeService.webpackJsonp.../node_modules/ng-pdf-make/pdfmake/pdfmake.service.js.PdfmakeService.open (pdfmake.service.js:15)
    at MyAppraisalsComponent.webpackJsonp../src/main/webapp/app/my-appraisals/my-appraisals.component.ts.MyAppraisalsComponent.downloadPDF (my-appraisals.component.ts:97)
    at Object.eval [as handleEvent] (MyAppraisalsComponent.html:1)
    at handleEvent (vendor.dll.js:12342)
    at callWithDebugContext (vendor.dll.js:13634)
    at Object.debugHandleEvent [as handleEvent] (vendor.dll.js:13222)
    at dispatchEvent (vendor.dll.js:9242)
    at vendor.dll.js:9834
    at HTMLButtonElement.<anonymous> (vendor.dll.js:28906)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)`

**Comment by pingli513** [comment] 2018-09-05 03:34
I am using ui-grid v4.6.3 and got issue when I click "Export all data to pdf" from my grid menu. From javascript console I am seeing "ReferenceError: pdfMake is not defined". Who could help me to solve the issue?

**Comment by BennyFranco** [comment] 2019-09-23 16:58
This was fixed in version **0.1.1** including the TS definitions for pdf-make

**Closed by BennyFranco** 2019-09-23 16:58 UTC
Labels: bug
